apiVersion: v1
kind: Pod
metadata:
  name: mistral-vllm-awq
spec:
  restartPolicy: Never
  tolerations:
  - key: sku
    operator: Equal
    value: gpu
    effect: NoSchedule
  containers:
  - name: vllm
    image: vllm/vllm-openai:latest
    args:
    - --model
    - TheBloke/Mistral-7B-Instruct-v0.2-AWQ
    - --quantization
    - awq
    - --dtype
    - float16
    - --max-model-len
    - "4096"
    ports:
    - containerPort: 8000
    resources:
      limits:
        nvidia.com/gpu: 1
